### ISSUE TITLE
Failure to install Ethetatom - "Error: only one instance of babel-polyfill is allowed"

### ISSUE THREAD

**Issue by Dashon-Hawkins** [0mkara/etheratom#114]
@0mkara @kevupton @ddcech @draku29 @raininja

[Enter steps to reproduce:]
_Note: I do have the 'language-babel 2.85.0' package installed_
Error told me to reference[ #91  > Failed to add etheratom package
](https://github.com/0mkara/etheratom/issues/91)
1. ...In Atom went to preferences and then, install (packages).
2. ...installed etheratom and upon install got the following error:

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [etheratom](https://github.com/0mkara/etheratom) package 4.3.3

### Stack Trace

Failed to activate the etheratom package

```
At only one instance of babel-polyfill is allowed

Error: only one instance of babel-polyfill is allowed
    at /packages/etheratom/build/main.js:36:9)
    at /packages/etheratom/build/main.js:5123:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/src/package.js:901:81)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at triggeredActivationHooks.forEach.hook (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:705:86)
    at Set.forEach (native)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:705:43)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
     -3:18.6.0 core:backspace (input.hidden-input)
     -3:08.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
aligner-css 1.2.1 
aligner-javascript 1.3.0 
altgr 0.1.0 
api-docs 0.0.6 
atom-agressive-js-iterable 0.1.1 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.32.5 
atom-cli-diff 1.9.0 
atom-clock 0.1.16 
atom-css-clean 2.24.1 
atom-css-comb 3.3.1 
atom-css-unit-converter 1.1.1 
atom-ide-ui 0.12.0 
atom-idea 1.2.2 
atom-javascript-console-snippets 0.10.0 
atom-meteor-file-snippets 2.0.0 
atom-meteor-snippets 0.1.0 
atom-nodejs-snippets 2.1.1 
atom-psql 0.28.0 
atom-react-alt-templates 0.6.0 
atom-react-instyle 0.2.8 
atom-react-intl-snippets 1.0.2 
atom-react-native-style 0.2.0 
atom-react-snippets 0.2.2 
atom-sql-list 0.3.1 
atom-ternjs 0.18.3 
atom-video 0.1.1 
atom-wordpress 0.3.0 
autocomplete-javascript 0.0.2 
autocomplete-meteor-packages 1.3.0 
autocomplete-solidity 0.3.4 
autocomplete-wordpress-hooks 0.2.3 
autumn-highlighter-syntax 1.13.0 
bdd-react-snippets 0.6.0 
beautify 0.31.0 
bem-levels 1.0.1 
bem-tools 0.1.15 
bemhtml 0.11.0 
bemjson-snippets 0.1.0 
bottom-dock 0.4.4 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
codelf 11.8.0 
css-color-name 0.4.0 
css-declaration-sorter 1.2.2 
css-from-html 0.1.5 
css-in-js 1.4.0 
css-skeleton-maker 0.1.4 
css-snippets 1.1.0 
css-specificity 0.2.2 
css-spy 0.6.0 
difile 0.3.4 
docblockr 0.13.7 
docker 0.8.0 
documentation-renderer 0.2.1 
duplicate-line-or-selection 0.9.0 
es6-javascript 1.0.0 
etheratom 4.3.3 
eval-javascript 1.2.0 
expand-region 0.4.0 
express-snippets 0.2.0 
expressjs 2.2.0 
fancy-react 0.6.3 
file-icons 2.1.21 
format-javascript-comment 0.2.5 
git-auto-stash 0.2.4 
git-control 0.9.0 
git-plus 7.10.2 
git-projects 1.17.0 
git-rebase 0.1.1 
git-time-machine 2.1.0 
gitlab 0.1.3-7 
gitlab-integration 0.4.7 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-shorcuts-react 3.0.3 
http-post 1.0.1 
Hydrogen 2.5.1 
hyperclick 0.0.0 
ide-bash 1.0.11 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-python 1.0.0 
ide-standardjs 0.0.1 
ide-vue 0.1.9 
imdone-atom 2.4.29 
imdone-atom-github 0.1.11 
impress 0.1.1 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
javascript-object-snippets 0.3.0 
javascript-refactor 0.7.1 
javascript-snippets 1.2.1 
javascript-standard-snippets 0.2.1 
jekyll 2.1.0 
jekyll-snippets 0.3.2 
jekyll-syntax-highlighting 0.1.0 
js-hyperclick 1.13.0 
language-babel 2.85.0 
language-diff 0.7.0 
language-documentation 2.0.1 
language-homebrew-formula 1.0.4 
language-javascript-jsx 0.3.7 
language-javascript-jxa 0.2.8 
language-javascript-plus 1.9.3 
language-mongodb 0.3.1 
language-patch 1.2.0 
language-pgsql 0.2.3 
language-sql-mysql 0.3.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-solidity 0.5.0 
linter-ui-default 1.7.1 
local-history 4.3.1 
local-server-express 0.3.1 
MagicPython 1.0.12 
mantrajs 0.5.0 
markdown-preview-plus 3.3.1 
markdown-writer 2.7.3 
materialize-css 0.5.1 
merge-conflicts 1.4.5 
meteor-api 2.20.0 
meteor-assist 0.3.0 
meteor-assist-sanuker 3.1.3 
meteor-helper 0.29.0 
meteor-open-all 0.4.0 
meteor-snippets 0.5.0 
meteor-spacebars 1.0.0 
meteorjs-snippets-es6 1.3.0 
minimap-git-diff 4.3.1 
modern-javascript-snippets 1.1.0 
my-express-nodejs 0.0.10 
new-file-plus 0.2.1 
node-on-fire 0.1.0 
node-requirer 0.1.12 
nucleon 1.0.4 
nuclide 0.317.0 
nuclide-esformatter 0.3.1 
nuclide-format-js 0.0.46 
nuclide-test-runner-cmd 0.1.0 
open-file-in 1.2.3 
pg-dev 0.8.2 
pg-formatter 0.0.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.3 
platomformio 0.7.1 
postcss-sorting 2.10.0 
project-plus 1.0.0 
Quick-JavaScript 2.2.0 
quick-query 0.13.0 
re-re-re-react 3.0.0 
react 0.18.0 
react-builder 0.0.1 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-function-to-class 0.2.4 
react-generatr 1.1.1 
react-native-components 0.1.1 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-redux-es6-snippets 0.1.3 
react-redux-react-native-snippets 0.2.4 
react-redux-snippets 0.1.6 
react-snippets 1.1.1 
redux-snippets 0.2.2 
repository-file-actions 0.7.0 
rest-client 1.3.1 
script 3.18.1 
split-diff 1.5.2 
styri-syntax 0.2.0 
talking-mango 0.2.1 
teletype 0.13.3 
todo-manager 0.2.10 
todo-show 2.3.0 
tool-bar 1.1.7 
tree-view-git-branch 0.1.2 
treedbox-atom-javascript 2.10.0 
turbo-javascript 1.4.0 
woocommerce 1.0.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.2.0 
wordpress-dictionary 4.4.0 
wordpress-suite 1.3.0 
wp-dev 0.3.5 
xatom-debug 1.6.11 
xatom-debug-chrome 0.7.4 
xatom-debug-nodejs 0.9.3 
zip-folder 3.2.0 
```

**Comment by 0mkara** [comment]
Fixed on 2d96bbe7636b23bfa6cd8f30302106d8ac9b3541
