### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by pencilso** [0mkara/etheratom#116]
Installing “etheratom@4.3.4” failed.Hide output…

> nodent-runtime@3.2.1 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\nodent-runtime
> node build.js

## Built C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\nodent-runtime/dist/index.js

> keccak@1.4.0 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\keccak
> node-gyp rebuild

C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\keccak\build\binding.sln]
"Keccak bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.5.0 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.5.0 rebuild C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\secp256k1
> node-gyp rebuild

C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\secp256k1\build\binding.sln]
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> sha3@1.2.2 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\sha3
> node-gyp rebuild

C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\sha3\build\binding.sln]
C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29
`-- (empty)

gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\keccak
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keccak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keccak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keccak
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\keccak\npm-debug.log
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\secp256k1
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.5.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.5.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\secp256k1\npm-debug.log
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\node_modules\etheratom\node_modules\sha3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\package.json'
npm WARN eslint-config-standard-jsx@1.2.1 requires a peer of eslint@^2.1.0 but none was installed.
npm WARN eslint-config-standard-jsx@1.2.1 requires a peer of eslint-plugin-react@>=2.7.1 but none was installed.
npm WARN apm-install-dir-118525-14240-1oio71b.iuap33ow29 No description
npm WARN apm-install-dir-118525-14240-1oio71b.iuap33ow29 No repository field.
npm WARN apm-install-dir-118525-14240-1oio71b.iuap33ow29 No README data
npm WARN apm-install-dir-118525-14240-1oio71b.iuap33ow29 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Administrator\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Administrator\\.atom\\.apmrc" "install" "C:\\Users\\Administrator\\AppData\\Local\\Temp\\d-118525-14240-ysdj5v.xqjg4lsor\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-14240-1oio71b.iuap33ow29\npm-debug.log
npm ERR! code 1

**Comment by 0mkara** [comment]
Try installing it from command line `apm install etheratom`. Although there are lots of reports that it does not install on windows.

**Comment by pencilso** [comment]
failed...
nodent-runtime@3.2.1 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\nodent-runtime
> node build.js

## Built C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\nodent-runtime/dist/index.js

> keccak@1.4.0 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\keccak
> node-gyp rebuild


C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã ��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\keccak\build\binding.sln]
"Keccak bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.5.0 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.5.0 rebuild C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\secp256k1
> node-gyp rebuild


C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã ��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\secp256k1\build\binding.sln]
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> sha3@1.2.2 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\sha3
> node-gyp rebuild


C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã ��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\sha3\build\binding.sln]
C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi
`-- (empty)


gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\keccak
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keccak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keccak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keccak
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\keccak\npm-debug.log
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\secp256k1
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.5.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.5.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\secp256k1\npm-debug.log
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\node_modules\etheratom\node_modules\sha3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\package.json'
npm WARN babel-loader@7.1.4 requires a peer of webpack@2 || 3 || 4 but none was installed.
npm WARN rollup-plugin-commonjs@9.1.3 requires a peer of rollup@>=0.56.0 but none was installed.
npm WARN apm-install-dir-118525-10692-dkq1px.2esi2dfgvi No description
npm WARN apm-install-dir-118525-10692-dkq1px.2esi2dfgvi No repository field.
npm WARN apm-install-dir-118525-10692-dkq1px.2esi2dfgvi No README data
npm WARN apm-install-dir-118525-10692-dkq1px.2esi2dfgvi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\etheratom\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Administrator\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Administrator\\.atom\\.apmrc" "install" "C:\\Users\\Administrator\\AppData\\Local\\Temp\\d-118525-10692-1ewi5sr.ux8o20529\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-118525-10692-dkq1px.2esi2dfgvi\npm-debug.log
npm ERR! code 1

**Comment by 0mkara** [comment]
Ok now try installing python and updating node version. This issue is similar to #36.
