### ISSUE TITLE
Installing etheratom 4.3.9 fails on Mac

### ISSUE THREAD

**Issue by bartleyg** [0mkara/etheratom#161]
```
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 3.7.0
git 2.15.2
```
```
$ node --version
v10.9.0
```
```
$ npm --version
6.2.0
```

```
$ apm install etheratom
Installing etheratom to /Users/bartley/.atom/packages ✗

> scrypt@6.0.3 preinstall /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/.staging/scrypt-7855b608
> node node-scrypt-preinstall.js


> nodent-runtime@3.2.1 install /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/etheratom/node_modules/nodent-runtime
> node build.js

## Built /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/etheratom/node_modules/nodent-runtime/dist/index.js

> keccak@1.4.0 install /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/etheratom/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/etheratom/node_modules/keccak
> node-gyp rebuild

Keccak bindings compilation fail. Pure JS implementation will be used.

> scrypt@6.0.3 install /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/etheratom/node_modules/scrypt
> node-gyp rebuild

/private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi
└── (empty)


npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/etheratom/node_modules/keccak
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 17.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/npm" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keccak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keccak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keccak
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/etheratom/node_modules/keccak/npm-debug.log
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/node_modules/etheratom/node_modules/scrypt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/package.json'
npm WARN apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi No description
npm WARN apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi No repository field.
npm WARN apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi No README data
npm WARN apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi No license field.
npm ERR! Darwin 17.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/bartley/.atom/.apm/.apmrc" "--userconfig" "/Users/bartley/.atom/.apmrc" "install" "/private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/d-118727-53748-1bmwgg9.u5cs3e4s4i/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/cg/d63t_4qx3hd4qp_xr43wxjr40000gn/T/apm-install-dir-118727-53748-10x4jy5.bag8ir7ldi/npm-debug.log
npm ERR! code 1
```

**Comment by 0mkara** [comment]
`gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.0, which is not supported by gyp.
`
Please try installing python 2

**Comment by bartleyg** [comment]
Python 2 is provided by default on Mac systems at /usr/bin/python. I also have it installed separately and linked to /usr/local/bin/python2. Neither were picked up. I would highly recommend removing any Python 2 dependencies in this day and age.

**Comment by 0mkara** [comment]
Thank you for your suggestion. Feel free to create a PR if you find any solution. There has been complain regarding this earlier. I will try removing Python 2 dependency once I find desired solution.
