### ISSUE TITLE
Linux Installation Issue

### ISSUE THREAD

**Issue by Higgsboson-X** [0mkara/etheratom#246]
`> scrypt@6.0.3 preinstall /home/chxw/worksite/etheratom/node_modules/scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install /home/chxw/worksite/etheratom/node_modules/scrypt
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/snap/atom/211/usr/share/atom/resources/app/apm/bin/node',
gyp verb cli   '/snap/atom/211/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/snap/atom/211/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /snap/atom/211/usr/share/atom/resources/app/apm/bin/python-interceptor.sh /snap/atom/211/usr/share/atom/resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/snap/atom/211/usr/share/atom/resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "2.7.15rc1\n"
gyp sill stripping "rc" identifier from version 
gyp verb get node dir compiling against --target node version: 2.0.16
gyp verb command install [ '2.0.16' ]
gyp verb install input version string "2.0.16"
gyp verb install installing version: iojs-2.0.16
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: iojs-2.0.16
gyp verb build dir attempting to create "build" dir: /home/chxw/worksite/etheratom/node_modules/scrypt/build
gyp verb build dir "build" dir needed to be created? /home/chxw/worksite/etheratom/node_modules/scrypt/build
gyp verb build/config.gypi creating config file
gyp sill build/config.gypi { target_defaults: 
gyp sill build/config.gypi    { cflags: [],
gyp sill build/config.gypi      default_configuration: 'Release',
gyp sill build/config.gypi      defines: [],
gyp sill build/config.gypi      include_dirs: [],
gyp sill build/config.gypi      libraries: [] },
gyp sill build/config.gypi   variables: 
gyp sill build/config.gypi    { asan: 0,
gyp sill build/config.gypi      coverage: false,
gyp sill build/config.gypi      debug_devtools: 'node',
gyp sill build/config.gypi      debug_http2: false,
gyp sill build/config.gypi      debug_nghttp2: false,
gyp sill build/config.gypi      force_dynamic_crt: 0,
gyp sill build/config.gypi      gas_version: '2.23',
gyp sill build/config.gypi      host_arch: 'x64',
gyp sill build/config.gypi      icu_data_file: 'icudt59l.dat',
gyp sill build/config.gypi      icu_data_in: '../../deps/icu-small/source/data/in/icudt59l.dat',
gyp sill build/config.gypi      icu_endianness: 'l',
gyp sill build/config.gypi      icu_gyp_path: 'tools/icu/icu-generic.gyp',
gyp sill build/config.gypi      icu_locales: 'en,root',
gyp sill build/config.gypi      icu_path: 'deps/icu-small',
gyp sill build/config.gypi      icu_small: true,
gyp sill build/config.gypi      icu_ver_major: '59',
gyp sill build/config.gypi      node_byteorder: 'little',
gyp sill build/config.gypi      node_enable_d8: false,
gyp sill build/config.gypi      node_enable_v8_vtunejit: false,
gyp sill build/config.gypi      node_install_npm: true,
gyp sill build/config.gypi      node_module_version: 57,
gyp sill build/config.gypi      node_no_browser_globals: false,
gyp sill build/config.gypi      node_prefix: '/',
gyp sill build/config.gypi      node_release_urlbase: 'https://nodejs.org/download/release/',
gyp sill build/config.gypi      node_shared: false,
gyp sill build/config.gypi      node_shared_cares: false,
gyp sill build/config.gypi      node_shared_http_parser: false,
gyp sill build/config.gypi      node_shared_libuv: false,
gyp sill build/config.gypi      node_shared_openssl: false,
gyp sill build/config.gypi      node_shared_zlib: false,
gyp sill build/config.gypi      node_tag: '',
gyp sill build/config.gypi      node_use_bundled_v8: true,
gyp sill build/config.gypi      node_use_dtrace: false,
gyp sill build/config.gypi      node_use_etw: false,
gyp sill build/config.gypi      node_use_lttng: false,
gyp sill build/config.gypi      node_use_openssl: true,
gyp sill build/config.gypi      node_use_perfctr: false,
gyp sill build/config.gypi      node_use_v8_platform: true,
gyp sill build/config.gypi      node_without_node_options: false,
gyp sill build/config.gypi      openssl_fips: '',
gyp sill build/config.gypi      openssl_no_asm: 0,
gyp sill build/config.gypi      shlib_suffix: 'so.57',
gyp sill build/config.gypi      target_arch: 'x64',
gyp sill build/config.gypi      uv_parent_path: '/deps/uv/',
gyp sill build/config.gypi      uv_use_dtrace: false,
gyp sill build/config.gypi      v8_enable_gdbjit: 0,
gyp sill build/config.gypi      v8_enable_i18n_support: 1,
gyp sill build/config.gypi      v8_enable_inspector: 1,
gyp sill build/config.gypi      v8_no_strict_aliasing: 1,
gyp sill build/config.gypi      v8_optimized_debug: 0,
gyp sill build/config.gypi      v8_promise_internal_field_count: 1,
gyp sill build/config.gypi      v8_random_seed: 0,
gyp sill build/config.gypi      v8_trace_maps: 0,
gyp sill build/config.gypi      v8_use_snapshot: true,
gyp sill build/config.gypi      want_separate_host_toolset: 0,
gyp sill build/config.gypi      nodedir: '/home/chxw/.atom/.node-gyp/.node-gyp/iojs-2.0.16',
gyp sill build/config.gypi      copy_dev_lib: true,
gyp sill build/config.gypi      standalone_static_library: 1,
gyp sill build/config.gypi      cache_lock_stale: '60000',
gyp sill build/config.gypi      ham_it_up: '',
gyp sill build/config.gypi      legacy_bundling: '',
gyp sill build/config.gypi      sign_git_tag: '',
gyp sill build/config.gypi      user_agent: 'npm/6.2.0 node/v8.9.3 linux x64',
gyp sill build/config.gypi      always_auth: '',
gyp sill build/config.gypi      bin_links: 'true',
gyp sill build/config.gypi      key: '',
gyp sill build/config.gypi      allow_same_version: '',
gyp sill build/config.gypi      description: 'true',
gyp sill build/config.gypi      fetch_retries: '2',
gyp sill build/config.gypi      heading: 'npm',
gyp sill build/config.gypi      if_present: '',
gyp sill build/config.gypi      init_version: '1.0.0',
gyp sill build/config.gypi      user: '',
gyp sill build/config.gypi      prefer_online: '',
gyp sill build/config.gypi      force: '',
gyp sill build/config.gypi      only: '',
gyp sill build/config.gypi      read_only: '',
gyp sill build/config.gypi      cache_min: '10',
gyp sill build/config.gypi      init_license: 'ISC',
gyp sill build/config.gypi      target: '2.0.16',
gyp sill build/config.gypi      editor: 'vi',
gyp sill build/config.gypi      rollback: 'true',
gyp sill build/config.gypi      tag_version_prefix: 'v',
gyp sill build/config.gypi      userconfig: '/home/chxw/.atom/.apmrc',
gyp sill build/config.gypi      cache_max: 'Infinity',
gyp sill build/config.gypi      timing: '',
gyp sill build/config.gypi      engine_strict: '',
gyp sill build/config.gypi      init_author_name: '',
gyp sill build/config.gypi      init_author_url: '',
gyp sill build/config.gypi      tmp: '/tmp',
gyp sill build/config.gypi      depth: 'Infinity',
gyp sill build/config.gypi      package_lock_only: '',
gyp sill build/config.gypi      save_dev: '',
gyp sill build/config.gypi      usage: '',
gyp sill build/config.gypi      metrics_registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      progress: '',
gyp sill build/config.gypi      otp: '',
gyp sill build/config.gypi      package_lock: 'true',
gyp sill build/config.gypi      https_proxy: '',
gyp sill build/config.gypi      save_prod: '',
gyp sill build/config.gypi      audit: 'true',
gyp sill build/config.gypi      cidr: '',
gyp sill build/config.gypi      onload_script: '',
gyp sill build/config.gypi      sso_type: 'oauth',
gyp sill build/config.gypi      rebuild_bundle: 'true',
gyp sill build/config.gypi      save_bundle: '',
gyp sill build/config.gypi      shell: '/bin/bash',
gyp sill build/config.gypi      dry_run: '',
gyp sill build/config.gypi      prefix: '/snap/atom/211/usr/share/atom/resources/app/apm',
gyp sill build/config.gypi      runtime: 'electron',
gyp sill build/config.gypi      scope: '',
gyp sill build/config.gypi      browser: '',
gyp sill build/config.gypi      cache_lock_wait: '10000',
gyp sill build/config.gypi      ignore_prepublish: '',
gyp sill build/config.gypi      registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      save_optional: '',
gyp sill build/config.gypi      searchopts: '',
gyp sill build/config.gypi      versions: '',
gyp sill build/config.gypi      cache: '/home/chxw/.atom/.apm',
gyp sill build/config.gypi      send_metrics: '',
gyp sill build/config.gypi      global_style: '',
gyp sill build/config.gypi      ignore_scripts: '',
gyp sill build/config.gypi      version: '',
gyp sill build/config.gypi      node_gyp: '/snap/atom/211/usr/share/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp',
gyp sill build/config.gypi      local_address: '',
gyp sill build/config.gypi      viewer: 'man',
gyp sill build/config.gypi      prefer_offline: '',
gyp sill build/config.gypi      color: 'true',
gyp sill build/config.gypi      no_proxy: '',
gyp sill build/config.gypi      sign_git_commit: '',
gyp sill build/config.gypi      fetch_retry_mintimeout: '10000',
gyp sill build/config.gypi      maxsockets: '50',
gyp sill build/config.gypi      offline: '',
gyp sill build/config.gypi      sso_poll_frequency: '500',
gyp sill build/config.gypi      umask: '0022',
gyp sill build/config.gypi      fetch_retry_maxtimeout: '60000',
gyp sill build/config.gypi      logs_max: '10',
gyp sill build/config.gypi      message: '%s',
gyp sill build/config.gypi      ca: '',
gyp sill build/config.gypi      cert: '',
gyp sill build/config.gypi      global: '',
gyp sill build/config.gypi      link: '',
gyp sill build/config.gypi      access: '',
gyp sill build/config.gypi      also: '',
gyp sill build/config.gypi      save: 'true',
gyp sill build/config.gypi      unicode: 'true',
gyp sill build/config.gypi      long: '',
gyp sill build/config.gypi      production: '',
gyp sill build/config.gypi      searchlimit: '20',
gyp sill build/config.gypi      unsafe_perm: 'true',
gyp sill build/config.gypi      update_notifier: 'true',
gyp sill build/config.gypi      auth_type: 'legacy',
gyp sill build/config.gypi      node_version: '8.9.3',
gyp sill build/config.gypi      tag: 'latest',
gyp sill build/config.gypi      git_tag_version: 'true',
gyp sill build/config.gypi      commit_hooks: 'true',
gyp sill build/config.gypi      script_shell: '',
gyp sill build/config.gypi      shrinkwrap: 'true',
gyp sill build/config.gypi      fetch_retry_factor: '10',
gyp sill build/config.gypi      save_exact: '',
gyp sill build/config.gypi      strict_ssl: 'true',
gyp sill build/config.gypi      globalconfig: '/home/chxw/.atom/.apm/.apmrc',
gyp sill build/config.gypi      dev: '',
gyp sill build/config.gypi      init_module: '/home/chxw/.atom/.node-gyp/.npm-init.js',
gyp sill build/config.gypi      parseable: '',
gyp sill build/config.gypi      globalignorefile: '/snap/atom/211/usr/share/atom/resources/app/apm/etc/npmignore',
gyp sill build/config.gypi      cache_lock_retries: '10',
gyp sill build/config.gypi      searchstaleness: '900',
gyp sill build/config.gypi      node_options: '',
gyp sill build/config.gypi      save_prefix: '^',
gyp sill build/config.gypi      scripts_prepend_node_path: 'warn-only',
gyp sill build/config.gypi      group: '1000',
gyp sill build/config.gypi      init_author_email: '',
gyp sill build/config.gypi      searchexclude: '',
gyp sill build/config.gypi      dist_url: 'https://atom.io/download/electron',
gyp sill build/config.gypi      git: 'git',
gyp sill build/config.gypi      optional: 'true',
gyp sill build/config.gypi      json: '' } }
gyp verb build/config.gypi writing out config file: /home/chxw/worksite/etheratom/node_modules/scrypt/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/chxw/worksite/etheratom/node_modules/scrypt/config.gypi
gyp verb common.gypi checking for gypi file: /home/chxw/worksite/etheratom/node_modules/scrypt/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /snap/atom/211/usr/share/atom/resources/app/apm/bin/python-interceptor.sh
gyp info spawn args [ '/snap/atom/211/usr/share/atom/resources/app/apm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/chxw/worksite/etheratom/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/snap/atom/211/usr/share/atom/resources/app/apm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/chxw/.atom/.node-gyp/.node-gyp/iojs-2.0.16/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/chxw/.atom/.node-gyp/.node-gyp/iojs-2.0.16',
gyp info spawn args   '-Dnode_gyp_dir=/snap/atom/211/usr/share/atom/resources/app/apm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/chxw/worksite/etheratom/node_modules/scrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/chxw/.atom/.node-gyp/.node-gyp/iojs-2.0.16
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/snap/atom/211/usr/share/atom/resources/app/apm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/snap/atom/211/usr/share/atom/resources/app/apm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/snap/atom/211/usr/share/atom/resources/app/apm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /snap/atom/211/usr/share/atom/resources/app/apm/node_modules/which/which.js:89:16
gyp ERR! stack     at /snap/atom/211/usr/share/atom/resources/app/apm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /snap/atom/211/usr/share/atom/resources/app/apm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/snap/atom/211/usr/share/atom/resources/app/apm/bin/node" "/snap/atom/211/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/chxw/worksite/etheratom/node_modules/scrypt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rollup-plugin-babel@4.1.0 requires a peer of rollup@>=0.60.0 <1 but none is installed. You must install peer dependencies yourself.
npm WARN rollup-plugin-commonjs@9.2.0 requires a peer of rollup@>=0.56.0 but none is installed. You must install peer dependencies yourself.
npm WARN remix-tests@0.1.1 requires a peer of yo-yoify@latest but none is installed. You must install peer dependencies yourself.
npm WARN etheratom@4.4.6 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chxw/.atom/.apm/_logs/2019-01-28T04_48_47_027Z-debug.log
`

**Comment by 0mkara** [comment]
`gyp ERR! stack Error: not found: make` I think you need to install build tools.
