### ISSUE TITLE
Compile stuck at "Compiling"

### ISSUE THREAD

**Issue by mallapurbharat** [0mkara/etheratom#263]
When I load the etheratom plugin and click on the "Compile" button, the button text changes to "Compiling" but it gets stuck forever at this phase. 

NOTE: Please see further info in below comments. This issue was fixed with help from @0mkara in Telegram chat. Adding this issue to document it for others.

**Comment by mallapurbharat** [comment]
As suggested by @0mkara, I hit "Ctrl+Shift+I" to load the developer's console window in atom. Below is the output from the console window....

```
Compiling contract... 
/home/bharat/.atom/packages/etheratom/build/main.js:958 Uncaught (in promise) TypeError: Cannot read property 'content' of undefined
    at Web3Helpers.compileWeb3 (/home/bharat/.atom/packages/etheratom/build/main.js:958:40)
    at Web3Env.compile (/home/bharat/.atom/packages/etheratom/build/main.js:5639:22)
    at compileSubscriptions.add.atom.workspace.observeTextEditors.editor (/home/bharat/.atom/packages/etheratom/build/main.js:5563:12)
    at Workspace.observeTextEditors (/usr/share/atom/resources/app/static/<embedded>:11:428089)
    at Web3Env.subscribeToCompileEvents (/home/bharat/.atom/packages/etheratom/build/main.js:5558:50)
    at HTMLElement.web3Subscriptions.add.atom.commands.add (/home/bharat/.atom/packages/etheratom/build/main.js:5413:12)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350055)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:348530)
    at CompileBtn._handleSubmit (/home/bharat/.atom/packages/etheratom/build/main.js:5245:25)
    at Object.ca (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:14:428)
    at ja (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:15:118)
    at ka (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:15:172)
    at wa (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:17:210)
    at Aa (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:18:248)
    at ya (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:18:57)
    at Da (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:21:69)
    at Ad (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:84:409)
    at Gi (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:250:397)
    at Kb (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:39:140)
    at Dd (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:86:249)
    at /home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:251:229
    at Object.exports.unstable_runWithPriority (/home/bharat/.atom/packages/etheratom/node_modules/scheduler/cjs/scheduler.production.min.js:18:163)
    at Ii (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:251:154)
    at Cd (/home/bharat/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:85:207)
```

**Comment by mallapurbharat** [comment]
As suggested by @0mkara, I could fix this issue by reloading atom, manually saving the .sol file using "Ctrl+s" and then hitting the "Compile" button. After this I could proceed to upload to the Ganache blockchain.

**Comment by 0mkara** [comment]
Keeping this open as this is an bug in our code. We are working on a fix.

**Comment by jalme** [comment]
Hi,

I have the same issue but is not even working by saving manually and then compiling.

Log from console below:
`Uncaught (in promise) TypeError: Cannot read property 'content' of undefined
    at Web3Helpers.compileWeb3 (/home/jalme/.atom/packages/etheratom/build/main.js:989)
    at Web3Env.compile (/home/jalme/.atom/packages/etheratom/build/main.js:8060)
    at compileSubscriptions.add.atom.workspace.observeTextEditors.editor (/home/jalme/.atom/packages/etheratom/build/main.js:7995)
    at Workspace.observeTextEditors (/usr/share/atom/resources/app/static/<embedded>:11)
    at Web3Env.subscribeToCompileEvents (/home/jalme/.atom/packages/etheratom/build/main.js:7990)
    at HTMLElement.web3Subscriptions.add.atom.commands.add (/home/jalme/.atom/packages/etheratom/build/main.js:7915)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11)
    at CompileBtn._handleSubmit (/home/jalme/.atom/packages/etheratom/build/main.js:5024)
    at Object.ka (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:15)
    at qa (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:15)
    at ra (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:16)
    at wa (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:16)
    at Aa (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:17)
    at ya (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:17)
    at Ba (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:17)
    at Kd (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:81)
    at hb (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:283)
    at Qd (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:83)
    at Hc (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:84)
    at Pd (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:84)
    at exports.unstable_runWithPriority (/home/jalme/.atom/packages/linter-ui-default/node_modules/scheduler/cjs/scheduler.production.min.js:18)
    at fg (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:120)
    at fb (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:283)
    at Nd (/home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:82)
compileWeb3 @ /home/jalme/.atom/packages/etheratom/build/main.js:989
compile @ /home/jalme/.atom/packages/etheratom/build/main.js:8060
compileSubscriptions.add.atom.workspace.observeTextEditors.editor @ /home/jalme/.atom/packages/etheratom/build/main.js:7995
observeTextEditors @ <embedded>:11
subscribeToCompileEvents @ /home/jalme/.atom/packages/etheratom/build/main.js:7990
web3Subscriptions.add.atom.commands.add @ /home/jalme/.atom/packages/etheratom/build/main.js:7915
handleCommandEvent @ <embedded>:11
dispatch @ <embedded>:11
_handleSubmit @ /home/jalme/.atom/packages/etheratom/build/main.js:5024
ka @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:15
qa @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:15
ra @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:16
wa @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:16
Aa @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:17
ya @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:17
Ba @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:17
Kd @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:81
hb @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:283
Qd @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:83
Hc @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:84
Pd @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:84
exports.unstable_runWithPriority @ /home/jalme/.atom/packages/linter-ui-default/node_modules/scheduler/cjs/scheduler.production.min.js:18
fg @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:120
fb @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:283
Nd @ /home/jalme/.atom/packages/linter-ui-default/node_modules/react-dom/cjs/react-dom.production.min.js:82
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: Object
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isSyncing: true}
/home/jalme/.atom/packages/etheratom/build/main.js:755  syncing:changed 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isBooleanSync: false}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isObjectSync: {…}}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isBooleanSync: false}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isObjectSync: {…}}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isBooleanSync: false}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isObjectSync: {…}}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isBooleanSync: false}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isObjectSync: {…}}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isBooleanSync: false}
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {syncStarted: true}
/home/jalme/.atom/packages/etheratom/build/main.js:753  syncing:data 
/home/jalme/.atom/packages/etheratom/build/main.js:716  New Message: {isObjectSync: {…}}`

**Comment by 0mkara** [comment]
@jalme we have a new patch for etheratom. Please update and if the error still exists lets have a small chat on our support channel [![Gitter](https://badges.gitter.im/Ethereum-Devtools-Developers-Studio/etheratom.svg)](https://gitter.im/Ethereum-Devtools-Developers-Studio/etheratom?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by jalme** [comment]
Open a new bug as requested https://github.com/0mkara/etheratom/issues/294
