### ISSUE TITLE
Uncaught TypeError: Cannot read property 'abiDefinition' of undefined

### ISSUE THREAD

**Issue by vjuge** [0mkara/etheratom#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v2.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'abiDefinition' of undefined

```
At /Users/vincent/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:325

TypeError: Cannot read property 'abiDefinition' of undefined
    at Object.callback (/Users/vincent/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:325:103)
    at /Users/vincent/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:142:25
    at /Users/vincent/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:89:9
    at XMLHttpRequest.request.onreadystatechange (/Users/vincent/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/httpprovider.js:110:13)
```

### Commands

```
     -3:27.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -2:26.5.0 eth-interface:compile (input.hidden-input)
  6x -2:23.9.0 eth-interface:toggle (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-source",
      "language-sql",
      "language-toml",
      "language-yaml",
      "meteor-api",
      "atom-ternjs",
      "linter-js-standard"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "atom-ethereum-interface": {
    "rpcAddress": "http://localhost:8545"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
atom-ethereum-interface, v2.0.0 (active)
atom-material-ui, v1.3.9 (inactive)
atom-ternjs, v0.16.1 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-json, v5.2.0 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-python, v1.8.26 (active)
autocomplete-solidity, v0.3.3 (active)
block-comment, v0.4.3 (inactive)
browser-plus, v0.0.87 (active)
docblockr, v0.9.1 (active)
file-icons, v2.0.9 (active)
git-plus, v7.1.1 (active)
highlight-selected, v0.12.0 (active)
language-babel, v2.49.4 (active)
language-ethereum, v0.3.9 (active)
linter, v1.11.21 (active)
linter-eslint, v8.0.0 (active)
linter-flake8, v2.1.4 (inactive)
linter-js-standard, v3.7.0 (inactive)
linter-solidity, v0.5.0 (active)
meteor-api, v2.20.0 (inactive)
minimap, v4.26.7 (active)
minimap-highlight-selected, v4.5.0 (active)
open-in-browsers, v0.0.19 (active)
open-recent, v5.0.0 (active)
open-terminal-here, v2.1.4 (inactive)
platformio-ide-terminal, v2.2.2 (active)
python-indent, v1.0.0 (active)
python-tools, v0.6.9 (active)
Remote-FTP, v0.9.4 (active)
rest-client, v1.3.1 (active)
save-session, v0.16.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (active)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (active)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by barkelyhwang** [comment]
I have the same status.
Atom Version: 1.13.0
Ubuntu 14.04 
FUTF-8Solidity
Uncaught ReferenceError: contractABI is not defined
/home/barkely/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:467
Hide Stack Trace
ReferenceError: contractABI is not defined
    at Object.constructFunctions (/home/barkely/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:467:9)
    at Constructor.componentDidMount (/home/barkely/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:653:42)
    at CallbackQueue.notifyAll (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/CallbackQueue.js:65:22)
    at ReactReconcileTransaction.close (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.closeAll (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.perform (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/Transaction.js:149:16)
    at batchedMountComponentIntoNode (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/ReactMount.js:282:15)
    at ReactDefaultBatchingStrategyTransaction.perform (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/Transaction.js:136:20)
    at Object.batchedUpdates (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/ReactUpdates.js:94:20)
    at Object._renderNewRootComponent (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/ReactMount.js:476:18)
    at Object._renderSubtreeIntoContainer (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/ReactMount.js:550:32)
    at Object.render (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/react/lib/ReactMount.js:570:23)
    at /home/barkely/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:677:38
    at Object.callback (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/contract.js:143:37)
    at /home/barkely/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:142:25
    at /home/barkely/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:89:9
    at XMLHttpRequest.request.onreadystatechange (/home/barkely/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/httpprovider.js:110:13)
