### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by yufu12345** [0mkara/etheratom#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package 2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/sundong/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.js:330

TypeError: Cannot read property 'getPath' of undefined
    at Object.compile (/packages/atom-ethereum-interface/lib/ethereum-interface.js:330:20)
    at /packages/atom-ethereum-interface/lib/ethereum-interface.js:90:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:09.6.0 eth-interface:compile (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-ethereum-interface 2.0.1 
linter-solidity 0.5.0 
```

**Comment by cyberhiker** [comment]
I'm getting this as well.  Compiles and deploys fine with Truffle.
