### ISSUE TITLE
Failed to activate the etheratom package

### ISSUE THREAD

**Issue by arthurcolle** [0mkara/etheratom#37]
[Enter steps to reproduce:]

1. ... Opened up Atom (1.16.0) ... thats it
Please consult earlier issue raised (likely related)

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [etheratom](https://github.com/0mkara/etheratom) package 4.0.0

### Stack Trace

Failed to activate the etheratom package

```
At soljson.cwrap is not a function

TypeError: soljson.cwrap is not a function
    at setupMethods (/Users/arthur/etheratom/node_modules/solc/wrapper.js:6:29)
    at Object.<anonymous> (/Users/arthur/etheratom/node_modules/solc/index.js:3:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/arthur/etheratom/lib/vm/vm.js:8:20)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.loadVM (/Users/arthur/etheratom/lib/ethereum-interface.js:55:21)
    at Object.load (/Users/arthur/etheratom/lib/ethereum-interface.js:47:8)
    at Object.activate (/Users/arthur/etheratom/lib/ethereum-interface.js:34:8)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:922:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/app.asar/src/package-manager.js:581:36)
    at /app.asar/src/package-manager.js:512:17
```

### Commands

```
```

### Non-Core Packages

```
atom-elixir 0.2.3 
atom-typescript 11.0.2 
autocomplete-elixir 1.5.14 
busy-signal 1.3.0 
etheratom 4.0.0 
intentions 1.1.2 
language-elixir 0.17.0 
linter 2.1.4 
linter-ui-default 1.2.3 
```

**Comment by arthurcolle** [comment]
#36 is previous issue I mentioned, thanks

**Comment by arthurcolle** [comment]
stupid node-gyp expects python2 in system. might have figured this one out - brb

**Comment by gh72029002** [comment]
I had this problem, but I did install react

#### START
Error: Cannot find module 'react'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/huwenfeng/Desktop/etheratom/lib/ethereum-interface-view.js:3:14)
    at Object.<anonymous> (/Users/huwenfeng/Desktop/etheratom/lib/ethereum-interface-view.js:139:6)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/huwenfeng/Desktop/etheratom/lib/ethereum-interface.js:4:20)
    at Object.<anonymous> (/Users/huwenfeng/Desktop/etheratom/lib/ethereum-interface.js:76:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/src/package.js:901:81)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerActivationHook (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:732:40)
### END

**Comment by 0mkara** [comment]
@gh72029002 how are you trying to install etheratom ?
