### ISSUE TITLE
Uncaught Error: METHOD_NOT_FOUND: The method being requested is not available on this server

### ISSUE THREAD

**Issue by inasacu** [0mkara/etheratom#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtcreators/atom-ethereum-interface) package, v0.1.3
### Stack Trace

Uncaught Error: METHOD_NOT_FOUND: The method being requested is not available on this server

```
At /Users/inasacu/Public/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61

Error: METHOD_NOT_FOUND: The method being requested is not available on this server
    at Object.module.exports.InvalidResponse (/Users/inasacu/Public/atom-ethereum-interface/node_modules/web3/lib/web3/errors.js:35:16)
    at [object Object].RequestManager.send (/Users/inasacu/Public/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/Users/inasacu/Public/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:145:58)
    at /Users/inasacu/Public/atom-ethereum-interface/lib/ethereum-interface.coffee:128:50
    at Object.module.exports.AtomSolidity.checkConnection (/Users/inasacu/Public/atom-ethereum-interface/lib/ethereum-interface.coffee:68:13)
    at Object.module.exports.AtomSolidity.compile (/Users/inasacu/Public/atom-ethereum-interface/lib/ethereum-interface.coffee:118:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (/Users/inasacu/Public/atom-ethereum-interface/lib/ethereum-interface.coffee:36:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -5:22.9.0 application:add-project-folder (atom-text-editor.editor.is-focused)
  2x -4:46.2.0 eth-interface:compile (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-ethereum-interface, v0.1.3
language-ethereum, v0.3.8

# Dev
No dev packages
```

**Comment by 0mkara** [comment]
Please verify solc is installed.
To check if solc installed, run `geth console` and execute `eth.getCompilers()` to find out if it is installed.
More details instruction can be found here [Compiling a contract](https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions#compiling-a-contract)

**Comment by inasacu** [comment]
Thanks.  Got it working.
