### ISSUE TITLE
installation issues on arch linux

### ISSUE THREAD

**Issue by nmiculinic** [0mkara/etheratom#46]
```
> sha3@1.2.0 install /tmp/apm-install-dir-117717-28324-rvkjje.dleul680k9/node_modules/etheratom/node_modules/sha3
> node-gyp rebuild

/tmp/apm-install-dir-117717-28324-rvkjje.dleul680k9
└── (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.6.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.12.6-1-ARCH
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-117717-28324-rvkjje.dleul680k9/node_modules/etheratom/node_modules/sha3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-117717-28324-rvkjje.dleul680k9/package.json'
npm WARN apm-install-dir-117717-28324-rvkjje.dleul680k9 No description
npm WARN apm-install-dir-117717-28324-rvkjje.dleul680k9 No repository field.
npm WARN apm-install-dir-117717-28324-rvkjje.dleul680k9 No README data
npm WARN apm-install-dir-117717-28324-rvkjje.dleul680k9 No license field.
npm ERR! Linux 4.12.6-1-ARCH
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/lpp/.atom/.apm/.apmrc" "--userconfig" "/home/lpp/.atom/.apmrc" "install" "/tmp/d-117717-28324-1ki6ohr.bve0q6ko6r/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117717-28324-rvkjje.dleul680k9/npm-debug.log
npm ERR! code 1
```

I'm on arch linux which has default python intrepreter as python3. Not sure how to fix this issue.

**Comment by 0mkara** [comment]
This is same as #36

**Comment by 0mkara** [comment]
Inactive for a while, closing!
