### ISSUE TITLE
Installing “etheratom@3.1.2” failed. - error TRK0005: Failed to locate: "CL.exe".

### ISSUE THREAD

**Issue by damiangreen** [0mkara/etheratom#58]
on Windows 10.
Curiously I installed  this yesterday on a different machine and it worked.
It apepars to be compaining about : error TRK0005: Failed to locate: "CL.exe".
I have Visual Studio 2017 installed and searchign for that file returns nothing.

`
> keccak@1.4.0 install C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\keccak
> node-gyp rebuild

C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\keccak\build\keccak.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\keccak\build\keccak.vcxproj]
  
  
"Keccak bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.4.0 install C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.4.0 rebuild C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\secp256k1
> node-gyp rebuild

C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\secp256k1\build\secp256k1.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\secp256k1\build\secp256k1.vcxproj]
  
  
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> sha3@1.2.0 install C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\sha3
> node-gyp rebuild

C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\sha3\build\sha3.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\sha3\build\sha3.vcxproj]
  
  
C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi
`-- (empty)

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\keccak
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keccak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keccak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keccak
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\keccak\npm-debug.log
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\secp256k1
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.4.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\secp256k1\npm-debug.log
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dddam\AppData\Local\atom\app-1.19.4\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\node_modules\etheratom\node_modules\sha3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\package.json'
npm WARN apm-install-dir-1171122-25852-12e5bnr.qublat6gvi No description
npm WARN apm-install-dir-1171122-25852-12e5bnr.qublat6gvi No repository field.
npm WARN apm-install-dir-1171122-25852-12e5bnr.qublat6gvi No README data
npm WARN apm-install-dir-1171122-25852-12e5bnr.qublat6gvi No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dddam\\AppData\\Local\\atom\\app-1.19.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\dddam\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\dddam\\.atom\\.apmrc" "install" "C:\\Users\\dddam\\AppData\\Local\\Temp\\d-1171122-25852-11l6ci6.b5yl5o2yb9\\package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dddam\AppData\Local\Temp\apm-install-dir-1171122-25852-12e5bnr.qublat6gvi\npm-debug.log
npm ERR! code 1`

**Comment by BriBarthelemy** [comment]
Hello,
Same issue here same environment.
Did you find a solution?

Thank you!

**Comment by damiangreen** [comment]
No, I switched to using VS Code instead

**Comment by boriskogan81** [comment]
+1
