### ISSUE TITLE
Cannot find module 'web3-requestManager'

### ISSUE THREAD

**Issue by visa10** [0mkara/etheratom#71]
At start of athom at i gives an error message.

Failed to activate the etheratom package. Cannot find module 'web3-requestManager'

```
Error: Cannot find module 'web3-requestManager'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/snap/atom/132/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/snap/atom/132/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///snap/atom/132/usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/snap/atom/132/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/valeriy/.atom/packages/etheratom/node_modules/web3/packages/web3-core/src/index.js:26:22)
    at Object.<anonymous> (/home/valeriy/.atom/packages/etheratom/node_modules/web3/packages/web3-core/src/index.js:88:3)
   .....................

```
 Etheratom "version": "3.4.0",
```
 apm  1.18.12
 npm  3.10.10
 node 6.9.5 x64
 atom 1.24.0
 python 2.7.12
 git 2.7.4
```

It is a problem with web3 the version. I tried to find the answer, but haven't found

**Comment by 0mkara** [comment]
Try installing it from command line `apm install etheratom`
If fails [install it from source](https://github.com/0mkara/etheratom#install-from-source)

**Comment by 0mkara** [comment]
@visa10 just released an update. Try installing etheratom from commandline `apm install etheratom`. That error should be fixed for now.
