### ISSUE TITLE
Uncaught TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by 0x4139** [0mkara/etheratom#86]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.2
**Thrown From**: [etheratom](https://github.com/0mkara/etheratom) package 4.0.9

### Stack Trace

Uncaught TypeError: Data must be a string or a buffer

```
At /Users/0x4139/.atom/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:17

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:74:16)
    at Clipboard.md5 (/private/var/folders/3n/3g0s58rd3k990bj0br6m3tb40000gn/T/AppTranslocation/90490C73-2665-4F20-B282-9AF7B1E8B5E6/d/Atom.app/Contents/Resources/app/src/clipboard.js:41:49)
    at Clipboard.write (/private/var/folders/3n/3g0s58rd3k990bj0br6m3tb40000gn/T/AppTranslocation/90490C73-2665-4F20-B282-9AF7B1E8B5E6/d/Atom.app/Contents/Resources/app/src/clipboard.js:52:44)
    at CoinbaseView._linkClick (/packages/etheratom/lib/components/CoinbaseView/index.js:45:24)
    at Object.ka (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:15:131)
    at Object.invokeGuardedCallback (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:16:137)
    at Object.invokeGuardedCallbackAndCatchFirstError (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:16:249)
    at Fa (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:20:303)
    at Ja (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:22:174)
    at La (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:22:335)
    at Ha (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:21:248)
    at Oa (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:24:79)
    at Pa (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:24:244)
    at Td (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:82:339)
    at batchedUpdates (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:186:434)
    at dc (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:42:377)
    at Xd (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:84:249)
    at interactiveUpdates (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:187:452)
    at Wd (/packages/etheratom/node_modules/react-dom/cjs/react-dom.production.min.js:83:203)
```

### Commands

```
     -2:21.3.0 core:move-right (input.hidden-input)
     -2:17.3.0 core:select-all (input.hidden-input)
     -2:12.9.0 eth-interface:activate (div.line)
  2x -1:54.9.0 core:undo (input.hidden-input)
     -1:53.4.0 core:save (input.hidden-input)
  2x -1:35.3.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:12.2.0 core:backspace (input.hidden-input)
 33x -0:49.7.0 core:undo (input.hidden-input)
     -0:40.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:38.7.0 editor:consolidate-selections (input.hidden-input)
     -0:38.7.0 core:cancel (input.hidden-input)
     -0:37.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:35.7.0 editor:consolidate-selections (input.hidden-input)
     -0:35.7.0 core:cancel (input.hidden-input)
     -0:32.7.0 intentions:highlight (input.hidden-input)
     -0:32.3.0 eth-interface:activate (input.hidden-input)
```

### Non-Core Packages

```
atom-solidity-linter 0.0.11 
busy-signal 1.4.3 
etheratom 4.0.9 
intentions 1.1.5 
linter 2.2.0 
linter-solidity 0.5.0 
linter-ui-default 1.7.1 
```

**Comment by 0mkara** [comment]
@0x4139 Can you please explain how you encountered this error ?
