### ISSUE TITLE
Failed to activate the etheratom package

### ISSUE THREAD

**Issue by raininja** [0mkara/etheratom#91]
```
Failed to activate the etheratom package
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Function (<anonymous>)
    at Object.<anonymous> (/home/raijin/.atom/packages/etheratom/node_modules/web3/packages/web3-core-requestmanager/src/givenProvider.js:29:14)
    at Object.<anonymous> (/home/raijin/.atom/packages/etheratom/node_modules/web3/packages/web3-core-requestmanager/src/givenProvider.js:88:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/raijin/.atom/packages/etheratom/node_modules/web3/packages/web3-core-requestmanager/src/index.js:30:21)
    at Object.<anonymous> (/home/raijin/.atom/packages/etheratom/node_modules/web3/packages/web3-core-requestmanager/src/index.js:246:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/raijin/.atom/packages/etheratom/node_modules/web3/packages/web3-core/src/index.js:26:22)
    at Object.<anonymous> (/home/raijin/.atom/packages/etheratom/node_modules/web3/packages/web3-core/src/index.js:88:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/raijin/.atom/packages/etheratom/node_modules/web3/src/index.js:32:12)
    at Object.<anonymous> (/home/raijin/.atom/packages/etheratom/node_modules/web3/src/index.js:91:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)

**Comment by raininja** [comment]
https://github.com/yhsiang/atom-js2ls/commit/69944d70dd59417c871a908765eec109352897e3

**Comment by raininja** [comment]
a similar issue 
https://github.com/GoogleChrome/puppeteer/issues/1229

**Comment by raininja** [comment]
only mention of 'unsafe-eval'
```
[raijin@ishtar][~/.atom/packages/etheratom]%grep unsafe-eval ./* -rn
./node_modules/handlebars/FAQ.md:17:  When not using the precompiler, Handlebars generates a dynamic function for each template which can cause issues with pages that have enabled Content Policy. It's recommended that templates are precompiled or the `unsafe-eval` policy is enabled for sites that must generate dynamic templates at runtime.

**Comment by 0mkara** [comment]
Etheratom does not use coffeescript so `js2coffee = allowUnsafeEval -> require 'js2coffee'` may not be the solution. All of these errors seems related to `web3-eth-accounts` package. Did you try installing with `apm install etheratom` ?

**Comment by raininja** [comment]
Yes that's how I was forced to install, as I had just used the --python option in apm
